-- Supabase table schema for individual_records

create table if not exists public.individual_records (
  id bigint generated by default as identity primary key,
  month text not null,
  s_no text,
  beneficiary_name text,
  father_husband_name text,
  cnic_number text,
  village_name text,
  union_council_name text,
  investment_business_plan text,
  amount numeric,
  recovery_amount numeric,
  receipt_number text,
  date text,
  deposit_slip_number text,
  deposit_date text,
  deposit_status text,
  beneficiary_status text,
  trade text,
  inserted_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create unique index if not exists individual_records_month_sno_idx on public.individual_records (month, s_no);
